const colors = require('tailwindcss/colors');
const defaultTheme = require('tailwindcss/defaultTheme');

module.exports = {
    mode: 'jit',
    content: ['./src/**/*.{html,js,svelte,ts}', './build/**/*.{html,js,svelte,ts}', './.svelte-kit/**/*.{html,js,svelte,ts}'],
    safelist: ['h-32', 'bottom-14', 'flex-column', 'flex-row', 'max-w-2xl', 'max-w-3xl', 'max-w-4xl', 'max-w-5xl', 'max-w-6xl', 'max-w-7xl', 'max-w-xl', 'm-3', 'm-6', 'p-3', 'pt-20', 'w-32', 'sm:m-3.5', 'sm:m-7', 'sm:p-3.5', 'md:m-4', 'md:m-8', 'md:p-4', 'md:pt-23', 'lg:m-4.5', 'lg:m-9', 'lg:p-4.5', 'lg:pt-26', 'xl:m-10', 'xl:m-5', 'xl:p-5', 'xxl:m-11', 'xxl:m-5.5', 'xxl:p-5.5', 'xxxl:m-12', 'xxxl:m-6', 'xxxl:p-5.5'],
    darkMode: 'class',
    theme: {
        container: {
            center: true,
        },
        screens: {
            sm: { min: '512px' },
            md: { min: '768px' },
            lg: { min: '1024px' },
            xl: { min: '1280px' },
            xxl: { min: '1560px' },
            xxxl: { min: '1920px' },
            portrait: { raw: '(orientation: portrait)' },
            landscape: { raw: '(orientation: portrait)' },
            print: { raw: 'print' },
        },
        extend: {
            colors: {
                transparent: 'transparent',
                current: 'currentColor',
                black: colors.black,
                white: colors.white,
                primary: colors.cyan,
                tertiary: colors.red,
                secondary: colors.violet,
                neutral: colors.gray,
                slate: colors.gray,
            },
            fontFamily: {
                sans: ['Inter var', ...defaultTheme.fontFamily.sans],
            },
            spacing: {
                1.75: '0.4375rem',
                2.25: '0.5625rem',
                2.75: '0.6875rem',
                3.25: '0.4375rem',
                4.5: '1.125rem',
                5.5: '1.375rem',
                6.5: '1.625rem',
                18: '4.5rem',
                23: '5.75rem',
                26: '6.5rem',
                37: '9.25rem',
                50: '12.5rem',
                51: '12.75rem',
                54: '13.5rem',
                60: '15rem',
                62: '15.5rem',
                64: '16rem',
                68: '17rem',
                70: '17.5rem',
                72: '18rem',
                76: '19rem',
                80: '20rem',
                88: '22rem',
                90: '22.5rem',
                98: '24.5rem',
                100: '25rem',
                108: '27rem',
                118: '29.5rem',
            },
        },
    },
    plugins: [require('@tailwindcss/typography'), require('@tailwindcss/aspect-ratio'), require('@tailwindcss/forms'), require('@tailwindcss/line-clamp'), require('tailwindcss-textshadow')],
    daisyui: {
        styled: true,
        themes: ['light', 'dark'],
        base: true,
        utils: true,
        logs: true,
        rtl: false,
        prefix: '',
        darkTheme: 'dark',
    },
};
